---

- name: wrapper playbook for kitchen testing "ansible-mysql-hardening"
  hosts: all
  become: true
  tasks:
    - name: install procps for debian systems
      apt:
        name: procps
        state: present
        update_cache: true
      when: ansible_distribution == 'Debian'

    - name: install required tools on SuSE
      zypper:
        name: "python-xml"
        state: present
      when: ansible_facts.os_family == 'Suse'

    - file:
        path: "/etc/mysql"
        state: directory
