---

- name: wrapper playbook for kitchen testing "ansible-mysql-hardening"
  hosts: all
  become: true
  tasks:
    - name: install procps for debian systems
      apt:
        name: procps
        state: present
        update_cache: yes
      when: ansible_distribution == 'Debian'

    - file:
        path: "/etc/mysql"
        state: directory
